version: "3"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./site.conf:/etc/nginx/conf.d/site.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./hello.html:/etc/nginx/index.html
    ports:
      - 80:80
